version: "3.3"

networks:
    devnet:
        external: true

services:

    web:
        build:
            context: .
            dockerfile: apache2.Dockerfile
        image: nuvei/kyc-lamp-apache
        container_name: web
        environment:
            TZ: "UTC"
        ports:
            - "80:80"
        volumes:
            - ./src:/srv/www
            - ./logs/apache:/var/log/apache2
            #- ./files/config/apache/apache2.conf:/etc/apache2/apache2.conf
            - ./files/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            # devnet network should be created before using _setup.bat script
            - devnet
        depends_on:
            - mysql
        restart: always

    php:
        build:
            context: .
            dockerfile: php.Dockerfile
        image: nuvei/kyc-lamp-php
        container_name: php
        volumes:
            - ./files/in_docker:/from_host
            - ./files/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
            - ./files/config/php${ONB_PHP_VERSION:-8.1}/php-fpm.ini:/etc/php/${ONB_PHP_VERSION:-8.1}/fpm/php.ini
            - ./files/config/php${ONB_PHP_VERSION:-8.1}/pool.d:/etc/php/${ONB_PHP_VERSION:-8.1}/fpm/pool.d
            - ./files/config/xdebug/xdebug.ini:/etc/php/${ONB_PHP_VERSION:-8.1}/mods-available/xdebug.ini
            - ./files/config/supervisor:/etc/supervisor/conf.d
            - ./logs:/var/log/php-fpm
            - ./logs/supervisor:/srv/logs/supervisor
            - ./src:/srv/www
        networks:
            # devnet network should be created before using _setup.bat script
            - devnet
        restart: always

    mysql:
        image: mariadb:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "andy"
            MYSQL_PASSWORD: "!APasswordHere"
            MYSQL_DATABASE: "kyc"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            # devnet network should be created before using _setup.bat script
            - devnet
        restart: always

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        volumes:
            - ./files/config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        restart: always
        networks:
            # devnet network should be created before using _setup.bat script
            - devnet
