version: "3"
services:
    web:
        build:
            context: .
            dockerfile: apache2.Dockerfile
        image: nuvei/kyc-lamp-apache
        container_name: web
        environment:
            TZ: "UTC"
        ports:
            - "8080:80"
        volumes:
            - ./files/config/apache/apache2.conf:/etc/apache2/apache2.conf
            - ./logs/apache:/var/log/apache2
            - ./src:/srv/www
        depends_on:
            - mysql
        restart: always
        
    php:
        build:
            context: .
            dockerfile: php.Dockerfile
        image: nuvei/kyc-lamp-php
        container_name: php
        volumes:
            - ./files/in_docker:/from_host
            - ./files/config/php${ONB_PHP_VERSION:-8.1}/php-fpm.ini:/etc/php/${ONB_PHP_VERSION:-8.1}/fpm/php.ini
            - ./files/config/php${ONB_PHP_VERSION:-8.1}/pool.d:/etc/php/${ONB_PHP_VERSION:-8.1}/fpm/pool.d
            - ./files/config/xdebug/xdebug.ini:/etc/php/${ONB_PHP_VERSION:-8.1}/mods-available/xdebug.ini
            - ./logs:/var/log/php-fpm
            - ./src:/srv/www
        restart: always
        
    mysql:
        image: mariadb:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "andy"
            MYSQL_PASSWORD: "!Andrei__"
            MYSQL_DATABASE: "kyc"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        volumes:
            - ./files/config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        restart: always

